name: "Cloud Run branch preview deployments with docker build and push to GCR"
description: "Authenticate with gcloud, build and push image to GCR and deploy as a new revision or branch preview to Cloud Run"
author: "Florian Schlittenbauer <florian.schlittenbauer@gmail.com>"
branding:
  icon: "arrow-up-circle"
  color: "green"
inputs:
  check_if_changed:
    description: "Set to true to check if working_directory has changes since the previous commit"
    required: false
    default: "false"
  working_directory:
    description: "Directory where the Dockerfile is to be found"
    required: true
    default: "."
  service_name:
    description: "Cloud run service name"
    required: true
  gcp_service_key:
    description: "GCP service key with storage and run permissions"
    required: true
  project:
    description: "GCP project"
    required: true
  registry:
    description: "GCP Registry (e.g. 'eu.gcr.io')"
    required: false
    default: eu.gcr.io
  region:
    description: "GCP region"
    required: false
    default: europe-west4
  env:
    description: "File path to environment configuration"
    required: false
runs:
  using: "docker"
  image: "docker://schliflo/github-action-cloud-run:latest"
